import clearTilesImage from '../../../../public/images/products/Clear Tiles.png';
import roadsTransportImage from '../../../../public/images/products/Roads & Transport.png';
import pastelTilesImage from '../../../../public/images/products/Pastel Tiles.png';
import rainbowTilesImage from '../../../../public/images/products/Rainbow Tiles.png';
import ballRunsImage from '../../../../public/images/products/Ball Runs.png';



export const connetixPacks = [
    // {
    //     image: rainbowRoadsImage,
    //     title: "Rainbow Roads Pack",
    //     description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
    //     buttonLabel: "Shop range",
    //     diamondColor: "bg-gray-100",
    //     diamondHoverColor: "group-hover:bg-gray-900",
    //     buttonColor: "bg-gray-300",
    //     buttonHoverColor: "group-hover:bg-gray-400",
    //     buttonTextColor: "text-gray-900",
    // },
    // {
    //     image: basePlateImage,
    //     title: "Base Plate Pack",
    //     description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
    //     buttonLabel: "Shop range",
    //     diamondColor: "bg-pink-100",
    //     diamondHoverColor: "group-hover:bg-pink-900",
    //     buttonColor: "bg-pink-300",
    //     buttonHoverColor: "group-hover:bg-pink-400",
    //     buttonTextColor: "text-pink-900",
    // },
    // {
    //     image: rainbowGeometricImage,
    //     title: "Rainbow Geometric Pack",
    //     description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
    //     buttonLabel: "Shop range",
    //     diamondColor: "bg-pink-100",
    //     diamondHoverColor: "group-hover:bg-pink-900",
    //     buttonColor: "bg-pink-300",
    //     buttonHoverColor: "group-hover:bg-pink-400",
    //     buttonTextColor: "text-pink-900",
    // },
    {
        image: clearTilesImage,
        title: "Clear Tiles",
        description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
        buttonLabel: "Shop range",
        diamondColor: "bg-blue-light",
        diamondHoverColor: "group-hover:bg-blue-tint",
        buttonColor: "bg-blue-300",
        buttonHoverColor: "group-hover:bg-blue-400",
        buttonTextColor: "text-blue-900",
    },
    // {
    //     image: rainbowCreativeImage,
    //     title: "Rainbow Creative",
    //     description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
    //     buttonLabel: "Shop range",
    //     diamondColor: "bg-green-100",
    //     diamondHoverColor: "group-hover:bg-green-900",
    //     buttonColor: "bg-green-300",
    //     buttonHoverColor: "group-hover:bg-green-400",
    //     buttonTextColor: "text-green-900",
    // },
    {
        image: roadsTransportImage,
        title: "Roads & Transport",
        description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
        buttonLabel: "Shop range",
        diamondColor: "bg-yellow-light",
        diamondHoverColor: "group-hover:bg-yellow-tint",
        buttonColor: "bg-yellow-light",
        buttonHoverColor: "group-hover:bg-yellow-tint",
        buttonTextColor: "text-orange-900",
    },
    {
        image: pastelTilesImage,
        title: "Pastel Tiles",
        description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
        buttonLabel: "Shop range",
        diamondColor: "bg-teal-light",
        diamondHoverColor: "group-hover:bg-teal-tint",
        buttonColor: "bg-teal-300",
        buttonHoverColor: "group-hover:bg-teal-400",
        buttonTextColor: "text-teal-900",
    },
    {
        image: rainbowTilesImage,
        title: "Rainbow Tiles",
        description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
        buttonLabel: "Shop range",
        diamondColor: "bg-primary-light",
        diamondHoverColor: "group-hover:bg-primary-tint",
        buttonColor: "bg-purple-300",
        buttonHoverColor: "group-hover:bg-purple-400",
        buttonTextColor: "text-purple-900",
    },
    {
        image: ballRunsImage,
        title: "Ball Runs",
        description: "Explore motion, gravity, cause & effect, plus so much more as you build and re-build your very own ball run designs!",
        buttonLabel: "Shop range",
        diamondColor: "bg-blue-light",
        diamondHoverColor: "group-hover:bg-blue-tint",
        buttonColor: "bg-indigo-300",
        buttonHoverColor: "group-hover:bg-indigo-400",
        buttonTextColor: "text-indigo-900",
    },
];
